### PR TITLE
Feature/1173 - Contents Download Instances

### PR DESCRIPTION
**Pull request by jrmartin**
Component to download instances media contents, with new requirement to display list of all instances.

### CODE REVIEW

**Comment by jrmartin** [comment]
Latest : 
image

**Review by ddelpiano — CHANGES_REQUESTED** [review]
```
Uncaught TypeError: Cannot read property 'values' of undefined
    at VFBDownloadContents.extractVariableFileMeta (VFBDownloadContents.js:91)
    at VFBDownloadContents.js:80
    at Array.map (<anonymous>)
    at VFBDownloadContents.handleDownload (VFBDownloadContents.js:79)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
    at executeDispatch (react-dom.development.js:389)
    at executeDispatchesInOrder (react-dom.development.js:414)
```

To reproduce, load medulla in the scene, open the download content component, unselect the template and select only image type (first from the types on top).
Click download and you will see the issue.

**Comment by jrmartin** [comment]
@ddelpiano Check for undefined/null objects added, the crash shouldn't happen anymore.

**Comment by ddelpiano** [comment]
closing this since it will be delivered with feature/1181 entirely

**Pull request closed without merging**
