### PR TITLE
Feature/560

### PR DESCRIPTION
**Pull request by jrmartin**
Circuit Browser component, used geppetto-client development branch.

### CODE REVIEW

**Comment by ddelpiano** [comment]
Re-assigned to @Robbie1977 and @gidili for review, this needs to be done after https://github.com/VirtualFlyBrain/geppetto-vfb/pull/651 .

@jrmartin once done with https://github.com/VirtualFlyBrain/geppetto-vfb/pull/651 could you please bring development into this PR as well?

Thx!

**Review by ddelpiano — CHANGES_REQUESTED** [review]
In the latest that I saw there wasn't the possibilty to delete an instance/neuron added in the configuration modal. We need an icon (bin beside the input text once the instance has been added/confirmed or something similar) to delete an instance/neuron currently configured.

**Comment by jrmartin** [comment]
> In the latest that I saw there wasn't the possibilty to delete an instance/neuron added in the configuration modal. We need an icon (bin beside the input text once the instance has been added/confirmed or something similar) to delete an instance/neuron currently configured.

When there's only 2 text field's to enter the neurons in the circuit browser configuration panel, the delete icon is not showing up since 2 neurons is the minimum required, user can still edit those text fields and update the neuron. The delete icon only shows where there's more than 2 Text fields in the circuit browser configuration panel. 

image

**Comment by jrmartin** [comment]
> Re-assigned to @Robbie1977 and @gidili for review, this needs to be done after #651 .
> 
> @jrmartin once done with #651 could you please bring development into this PR as well?
> 
> Thx!

Development branch merge into this one, ready for review.

**Pull request merged**
