### PR TITLE
#1268 Clear circuit browser filters

### PR DESCRIPTION
**Pull request by jrmartin**
Clear filters when neurons are reversed or cleared using the 'clear button'

### CODE REVIEW

**Review by Robbie1977 — APPROVED** [review]

**Review by Robbie1977 — DISMISSED** [review]
Does this rely on a different Geppetto repo? as failing hard when deployed on https://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto

**Comment by Robbie1977** [comment]
```
TypeError: this.setupCamera is not a function
    at new e (main.bundle.js:297)
    at Canvas.value (main.bundle.js:17)
    at il (common.bundle.js:46)
    at ds (common.bundle.js:46)
    at t.unstable_runWithPriority (common.bundle.js:54)
    at Bo (common.bundle.js:46)
    at ps (common.bundle.js:46)
    at Zl (common.bundle.js:46)
    at Ql (common.bundle.js:46)
    at Is (common.bundle.js:46)
```

**Comment by Robbie1977** [comment]
FYI using https://github.com/VirtualFlyBrain/geppetto-vfb/blob/feature/1268/Dockerfile#L19

**Comment by jrmartin** [comment]
@Robbie1977 I'll check this today, it doesn't rely on a different geppetto version, weird we are getting this error now.

**Comment by ddelpiano** [comment]
the autocomplete does not work anymore for me in the circuit browser?
@Robbie1977 is this related to the solr server?

@jrmartin could you check this is Robb confirms that is fine please? 
I tested this from both development and the feature branch opened for the PR. 

Thanks

**Comment by Robbie1977** [comment]
Failure is fine just the graph has moved slightly - my need to evaluate testing this snapshot (dev pdb had updated so expected) 
image

**Comment by Robbie1977** [comment]
@ddelpiano @jrmartin Sorry ignore the SOLR it's got missing annotation so no results returned - I'll fix it

**Comment by Robbie1977** [comment]
@ddelpiano @jrmartin dev SOLR is now fixed.

**Review by ddelpiano — CHANGES_REQUESTED** [review]
@jrmartin this still does not work for me, if I search for FAFB, select the first result, then re-click on the first input text, delete that neuron and search for jrch I got no results when in reality I should since I am not hooked up on any dataset anymore.

**Comment by ddelpiano** [comment]
Waiting to test this until the new facets annotation will be available with the solr data - @Robbie1977 could you ping me once these are available (even a subset to test the feature will be enough for me), thanks!

**Pull request merged**
